* Lasagne
(200g Karotten) und (200g Sellerie) reiben (100g Speckwürfel) braten,
abtropfen (600g Gehacktes Rindfleisch( portionsweise braten
Hackfleisch mit (1El. Mehl) bestäuben Hitze von Hackfleisch reduzieren
(2 Zwiebeln), (2Zehen Knoblauch) und (4El. Tomatenpüree) dämpfen
Hackfleisch hinzugeben (2.5dl Rotwein) und (2.5dl Fleischbouillon)
dazugeben aufkochen (1 Lorbeerblatt) und (0.2Tl. Zucker) und
(2El. Rosmarinnadeln) und (2El. Majoranblätter) und (1Tl. Salz) und
(1Tl. Pfeffer) dazugeben rühren, zudecken, schmoren ~ca. 1h 1
Lorbeerblatt entfernen (40g Butter) warm werden lassen, bei niedriger
Hitze Mehl unterrühren (6dl Milch) hinzugeben (0.75Tl) hinzugeben
(0.2Tl Pfeffer) hinzugeben rühren, köcheln ~ca. 10min.  1/3
Béchamel-Sauce auf Boden verteilen (3 Pastablatt) bedecken Hackfleisch
Mischung in 5 Portionen unterteilen Hackfleisch, (3 Pastablatt)
Einwenig Béchamel-Sauce draufgeben Letzte Portion Hackschleisch
Letztes (1 Pastablatt) Rest Béchamel-Sauce draufgiesen (70g Parmesan)
draufstreuen backen 220° ~30min
* Teriyaki Poulet
Geriebene Limettenschale, ½ Limettensaft von (1 Limtette) (10g ingwer)
schälen, (1zehe knoblauch) pressen. Ingwer, Knoblauch und (2El
Teriyaki-Sauce), (2El Öl), (0.25Tl Peffer) in eine Schüssel geben
verrühren (300g Poulet) zerschneiden. Marinade einmassieren Poulet
braten ~ 5 min Zucker bestreuen → rühren Marinade, (0.75dl Wasser),
(0.75dl Teriyaki-Sauce) ablöschen köcheln lassen ~7min
* Rotes Curry
(300g Poulet), (1 Peperoni), (1 Mais-Kölbchen), (1 Zwiebel), (1Zehe
Knoblauch), (0.10 Chli), (0.5 Lauch) in kleine Stücke
schneiden. (250ml Kokusmilch) erwärmen und (1tl Rote Curry Paste)
untermischen. Leicht aufköcheln lassen, danach (100ml Soja-Sauce)
hinzugeben. Anschliessen das gehackte Matrial hinzugeben. Köcheln
lassen ~ 7min. Daraufhin mit (0.5 Zitronengras), (0.25tl Fisch-Sauce)
abstimmen.
* Chesse Buger
(300g Hackfleisch(Rind)) vorbereiten. (200g Emmentaler-Käse)
zuschneiden. (40g Salat) abtrennen. (2scheiben Brot) vorbereiten und
(1 Zwiebel) klein schneiden. Anschliessend Fleisch zu runden scheiben
formen und anbraten. Anschliessend den Emmentaler-Käse drauflegen.
* Älpemagerone
Grosser Topf mit Wasser aufsetzen und (2El Salz hinzugeben). (300g
Kartoffel) schälen und zu Mundstücke schneiden. Sobald das Wasser
kocht die Kartoffel hinzugeben. ca. ~7min später (250g Magronen)
beifügen. (250g Emmentaler-Käse) reiben. (250ml Wasser) in einer
weiteren Pfanne aufsetzen. (1 Kräuterwürfel) und (250ml Rahm)
hinzugeben. Anschliessend mit (1Tl Moskat-Nuss) abschmecken. Sauce bei
schwacher Flamme köcheln lassen. Sobald Kartoffel durch sind,
schrittweise absieben und in einen Ofentopf geben. Für jedes sieb eine
Lage Käse drüber streuen. Sobald alle Magronen und Kartoffel gesiebt
sind und der Käse aufgebraucht ist. Die Sauce
hinzugeben. Anschliessend das ganze für 10min in Backofen bei 150° backen.
* Himbeertorte
(150g Zucker), (5 Ei)-gelb, (1El Wasser)(warm) mit Schwingbesen
verrühren bis schaumig. Zitronenschale von (1 Zitrone) darunterrühren.
5xEiweiss mit wenig Salz steifschlagen. (62g Zucker) beigeben,
weiterschlagen bis Schnee glänzt. (40g Mandeln), (4El Mehl) mischen.
Lagenweise Gemisch und Schnee auf Schaum geben alles sorgfältig rühren
in Form füllen backen ~35min bei 180° im mittlers Fach. Form
entfernen, auskühlen. Biskuit *QUER* halbieren (400g Himbeeren) mit
(4El Puderzucker), (1El Zirtronensaft) pürieren, und sieben. Saft in
einen Messbecher geben hälfte in Pfann.  Messbecher Saft mit (6dl
Rahm) steifschlagen 2/3 Rahmgemisch mit (200g Himbeeren) auf
Biskuitboden verteilen 1/3 Rahmgemisch kühlstellen (60g Zucker) und
(2Tl Geliermittel) zum Pfannengemisch dazubenen und rühren
anschliessend kochen für 2min. Pfannengemisch auf Torte verteilen.
Torte für 20-40min kühlen. Tortenrand mit Restrahm bestreichen
Mandeln, (12g Himbeeren) verziehren
