* Lasagne
(200g carrots) and (200g celery) grate (100g bacon cubes) fry,
Drain (600g minced beef (fry in portions)
Dust minced meat with (1 egg flour) Reduce heat from minced meat
Steam (2 onions), (2 cloves of garlic) and (4 tbsp tomato puree)
Add minced meat (2.5dl red wine) and (2.5dl meat broth)
bring to the boil (1 bay leaf) and (0.2 t sugar) and
(2El Rosmarinnadeln) and (2El .Majoranblätter) and (1Tl Salt) and
Add (1 tsp pepper), cover, stew ~ ca. 1h 1
Remove bay leaf (40g butter), warm at low
Stir in the flour (6dl of milk) (0.75Tl)
Add (0.2 tsp pepper) stir, simmer ~ approx. 10min. 3.1
Spread béchamel sauce on the ground (3 pasta leaves) cover minced meat
Mix in 5 portions subdue minced meat, (3 pastel leaves)
Add a little béchamel sauce. Last portion of minced meat
Last (1 pasta leaf) leftover Béchamel sauce (70g Parmesan)
Sprinkle on the cake 220 ° ~ 30min
* Teriyaki chicken
Grated lime zest, ½ lime juice of (1 Limtette) (10g ginger)
peel, (1zehe garlic) squeeze. Ginger, garlic and (2El
Teriyaki sauce), (2 tbsp oil), (0.25 tsp pepper) in a bowl
stir (300g chicken) cut. Marinade massaging chicken
fry ~ sprinkle with sugar for 5 minutes → stir marinade, (0.75dl water),
Deglaze (0.75dl teriyaki sauce) to simmer ~ 7min
* Red curry
(300g chicken), (1 pepperoni), (1 corn-cubes), (1 onion), (1zhe
Garlic), (0.10 Chli), (0.5 leek) into small pieces
to cut. (250ml coconut milk) and (1tl red curry paste)
Mix in. Simmer gently, then (100ml soy sauce)
add. Then add the minced matrial. simmer
let ~ 7min. Then with (0.5 lemongrass), (0.25tl fish sauce)
vote.
* Chesse Buger
(300g of minced beef). (200g Emmentaler cheese)
cut. (40g salad). Prepare (2-slice bread) and
Chop (1 onion). Then meat to round slices
mold and fry. Then add the Emmentaler cheese.
* Älpemagerone
Place large pot of water and add 2 tablespoons of salt. (300g
Peel and cut into mouthpieces. Once the water
cooks to add the potato. ~ 7min later (250g Magronen)
add. (250g Emmentaler cheese). (250ml of water) in one
put on another pan. (1 herb cube) and (250ml cream)
add. Then season with (1 tl of musk nut). Sauce at
simmer with a gentle flame. Once potatoes are through,
gradually sieve and place in an oven pot. One for each sieve
Lay cheese over it. Once all the magronas and potatoes are sifted
are and the cheese is used up. The sauce
add. Then bake the whole for 10min in oven at 150 °.
* Raspberry cake
(150g sugar), (5 egg) -gelb, (1El water) (warm) with whisk
stir until frothy. Add the lemon peel of (1 lemon).
Whisk 5x egg whites with a little salt. Add (62g sugar),
continue beating until snow shines. (40g almonds), (4El flour) mix.
Layer by layer mixture and add snow on foam stirring everything carefully
Fill in the form of baking ~ 35min at 180 ° in the middle compartment. shape
remove, cool. Biscuit * CRANGE * halve (400g raspberries) with
Puree (4 spoonfuls of icing sugar), (1 spoonful of zirconium juice), and seven. Juice in
put a measuring cup half in Pfann. Measuring cup of juice with (6dl
Cream) stiff 2/3 cream mixture with (200g raspberries) on
Spread the biscuit bottom 1/3 cream mixture cold spots (60g sugar) and
(2Tl gelling agent) to the pan mixture and stir
then cook for 2min. Distribute pan mixture on cake.
Cake for 20-40min cool. Spread the cake with cream
Almonds, (12g raspberries) verziehren
